base_url = "https://tango.n1gp.net"

[languages.en.translations]
menu-blog = "Blog"
menu-status = "Status"
menu-github = "GitHub"
menu-language = "Language"
home-unsupported = '<strong>Tango is feature-complete and no longer in development.</strong> Community-sourced updates are welcome.'
home-first-time = '<strong>First time here?</strong> For support and matchmaking, please join the <a href="https://discord.n1gp.net" target="_blank">N1GP</a> Discord server!'
home-tagline = "The old new Mega Man Battle Network experience."
home-lead = "Play Mega Man Battle Network online with rollback netcode."
home-download-button = "Download"
home-download-button-toggle-dropdown = "Toggle dropdown"
home-download-notice = 'You must have a copy of either <a href="https://store.steampowered.com/sub/821963/?l=english" target="_blank">Mega Man Battle Network Legacy Collection</a> on Steam. The Tango developers <strong>do not condone piracy of any kind</strong>.'
home-post-download-cta = "… then, join a community below to start playing!"
home-panel-1-title = "Supports all games"
home-panel-1-description = "Works with every English and Japanese Battle Network game."
home-panel-2-title = "Rollback netcode"
home-panel-2-description = "Smooth netplay with minimal lag, no matter the distance."
home-panel-3-title = "Automatic replays"
home-panel-3-description = "Get automatic, accurate replays of all your matches."
home-panel-4-title = "Automatic ROM patching"
home-panel-4-description = "Play online with your favorite custom patches."
home-panel-5-title = "100% saves included"
home-panel-5-description = "Build your dream folder immediately."
home-panel-6-title = "Simple matchmaking"
home-panel-6-description = "Just share your link code and start playing."
footer = 'Mega Man Battle Network is a trademark of <a href="https://www.capcom.com" target="_blank" class="text-white">CAPCOM CO., LTD</a>. Tango is a fan project and is not affiliated with, funded, or in any way associated with Capcom.'

[languages.ja.translations]
menu-blog = "ブログ"
menu-status = "ステータス"
menu-github = "GitHub"
menu-language = "言語"
home-unsupported = '<strong>Tangoは開発者による積極的なサポートは終了しています。</strong>Tangoのアップデートの予定はありません。'
home-first-time = '<strong>ここは初めてですか？</strong>導入方法や対戦相手については、是非とも<a href="https://discord.gg/yF2gZfM8Dr" target="_blank">EXE Hello Hello Mango Coconut</a>のDiscordサーバーへご参加ください！'
home-tagline = "ロックマンエグゼの古新体験"
home-lead = "一緒に「ロックマンエグゼ」をロールバックネットコードでオンラインプレイしましょう！"
home-download-button = "ダウンロード"
home-download-button-toggle-dropdown = "トグルドロップダウン"
home-download-notice = 'Tangoはロックマンエグゼの対戦を拡張する対戦特化ツールです。 Tangoで遊ぶにはSteam版「<a href="https://store.steampowered.com/sub/821963/?l=japanese" target="_blank">ロックマンエグゼ アドバンスドコレクション</a>」が必要です。Tangoの開発者は、<strong>いかなる種類の著作権侵害も容認していません</strong>。'
home-post-download-cta = "次に、以下のいずれかのコミュニティへ参加してプレイを始めましょう!"
home-panel-1-title = "全部作品対応可能"
home-panel-1-description = "英語と日本語のすべてのエグゼ作品に対応しています。"
home-panel-2-title = "ロールバックネットコード"
home-panel-2-description = "距離に関係なく、最小限のラグでプレイすることができます。"
home-panel-3-title = "自動リプレイ録画"
home-panel-3-description = "対戦を完璧な精度で自動的に記録します。"
home-panel-4-title = "自動ROMパッチ"
home-panel-4-description = "カスタムパッチでオンラインプレイできます。"
home-panel-5-title = "100％セーブファイルを含む"
home-panel-5-description = "すぐに夢の構築を作ることができます。"
home-panel-6-title = "簡単なマッチメイキング"
home-panel-6-description = "リンクコードを共有するだけで、プレイを始めます。"
footer = '「ロックマンエグゼ」は<a href="https://www.capcom.com" target="_blank" class="text-white">CAPCOM CO., LTD</a>の商標です。Tangoはファンプロジェクトであり、CAPCOMとは一切関係ありません。'

[languages.zh-CN.translations]
menu-blog = "博客"
menu-status = "状态"
menu-github = "GitHub"
menu-language = "语言"
home-unsupported = '<strong>Tango不再由开发者提供支持。</strong>Tango将不再更新。'
home-first-time = '<strong>第一次来？</strong>关于支持和对手配对，请加入<a href="https://jq.qq.com/?_wv=1027&k=we2L9Epb" target="_blank">QQ群310432370：洛克人EXE对战大会</a>！'
home-tagline = "洛克人EXE的旧新体验"
home-lead = "使用回滚净码跟朋友一起《洛克人EXE》网络对战！"
home-download-button = "下载"
home-download-button-toggle-dropdown = "切换下拉菜单"
home-download-notice = '你必须有Steam上的《<a href="https://store.steampowered.com/sub/821963/?l=schinese" target="_blank">ROCKMAN EXE 合集</a>》。Tango的开发者<strong>不容忍任何形式的盗版行为</strong>。'
home-post-download-cta = "然后，加入以下任何的群开始玩！"
home-panel-1-title = "支持所有EXE游戏"
home-panel-1-description = "支持所有英文版和日文版的洛克人EXE游戏。"
home-panel-2-title = "回滚网络代码"
home-panel-2-description = "顺畅的网络游戏，无论距离多少。"
home-panel-3-title = "自动回放记录"
home-panel-3-description = "自动记录所有战斗的精确回放。"
home-panel-4-title = "自动ROM补丁"
home-panel-4-description = "用你的自定义补丁进行在线游玩。"
home-panel-5-title = "包含100%保存文件"
home-panel-5-description = "立即建立你的梦想配置。"
home-panel-6-title = "简单配对"
home-panel-6-description = "只要分享你的链接代码并开始游戏。"
footer = '《洛克人EXE》是<a href="https://www.capcom.com" target="_blank" class="text-white">CAPCOM CO., LTD</a>的商标。Tango是粉丝项目，与CAPCOM无关。'

[languages.es.translations]
menu-blog = "Blog"
menu-status = "Estado"
menu-github = "GitHub"
menu-language = "Lenguaje"
home-unsupported = '<strong>Tango ya no recibe soporte activo por parte del desarrollador.</strong> No se esperan más actualizaciones de Tango.'
home-first-time = '<strong>¿Es tu primera vez aquí?</strong> Para asistencia y matchmaking, únete al servidor Discord de <a href="https://discord.gg/cKgTcvz" target="_blank">Net Saviors</a>.'
home-tagline = "La vieja nueva experiencia en Mega Man Battle Network."
home-lead = "Juega Mega Man Battle Network online usando netcode rollback."
home-download-button = "Descargar"
home-download-button-toggle-dropdown = "Usar dropdown"
home-download-notice = '<a href="https://store.steampowered.com/sub/821963/?l=spanish" target="_blank">Mega Man Battle Network Legacy Collection</a> en Steam. Los desarrolladores de Tango <strong>no aprueban ningún tipo de piratería</strong>.'
home-post-download-cta = "… entonces, ¡únete a una comunidad a continuación para empezar a jugar!"
home-panel-1-title = "Soporte para todos los juegos"
home-panel-1-description = "Soporta todos los juegos de la Battle Network inglesa y japonesa."
home-panel-2-title = "Netcode con Rollback"
home-panel-2-description = "Suave experiencia de juego, con lag minimo, sin importar la distancia."
home-panel-3-title = "Repeticiones automaticas"
home-panel-3-description = "Obten repeticiones automaticas y precisas de todas tus partidas."
home-panel-4-title = "Parchado de ROMs automatico"
home-panel-4-description = "Juega en linea usando tus parches favoritos."
home-panel-5-title = "100% guardadas incluido"
home-panel-5-description = "Construya inmediatamente el folder de sus sueños."
home-panel-6-title = "Emparejamiento sencillo"
home-panel-6-description = "Sólo tienes que compartir el código de tu enlace y empezar a jugar."
footer = 'Mega Man Battle Network es una marca registrada de <a href="https://www.capcom.com" target="_blank" class="text-white">CAPCOM CO., LTD</a>. Tango es un proyecto de fans y no se encuentra afiliado, financiado o asociado a Capcom de ninguna forma.'
